### ISSUE TITLE
Initialize API Gateway backend

### ISSUE THREAD

**Issue by lucassgomes** [lucassgomes/diobank#3]
- [Use Apache Kafka](https://kafka.apache.org/documentation/)
- [Use Kafkajs](https://kafka.js.org/docs/getting-started)
- Docker for Apache Kafka

**Comment by cataua** [comment]
Estou com uma dúvida, devido a minha interpretação errada do que seria o microserviço, eu crio o consumer nos módulos, ou crio um módulo que vai se comunicar com esses outros?

**Comment by lucassgomes** [comment]
#4 Finish
